export const environment = {
  production: true,
  PROVIDER:'https://data-seed-prebsc-1-s1.binance.org:8545',
  CONTRACT_ADDRESS:'0xA0343a5dDA36aAc6F17Ef9911d7808A4426f2616',
  TOKENSALE_ADDRESS:'0xd9a9944F13969D34f3ea3238b50983b274aaDea3',
  LOGO:'assets/images/logo.png',
  TITLE:'Columbus Token Crowdsale',
  NETWORK:'BSC',
  TYPE:'TESTNET',
  FROMTOKENNAME:'BNB',
  TOTOKENNAME:'CBS',
  TRANSLINK:'https://bscscan.com/tx',
  SUPPORTMAIL:'support@columbustoken.net',
  FACEBOOK:'https://www.google.com/',
  INSTAGRAM:'https://www.google.com/',
  PINTEREST:'https://www.google.com/',
  TWITTER:'https://www.google.com/',
  GOOGLE:'https://www.google.com/',
  WHATSAPP:'https://www.google.com/',
  LINKEDIN:'https://www.google.com/',
};
